### ISSUE TITLE
Cannot import "disabled" from textual

### ISSUE THREAD

**Issue by alansill** [davidbrochart/jpterm#49]
I installed jpterm in a fresh conda environment by first installing pip and then "pip install jpterm" and receive the following message when issuing the "jpterm" command:

```
Traceback (most recent call last):
  File "/home/asill/conda/envs/jpterm/bin/jpterm", line 5, in <module>
    from jpterm.cli import main
  File "/home/asill/conda/envs/jpterm/lib/python3.12/site-packages/jpterm/cli.py", line 3, in <module>
    from txl.app import disabled
ImportError: cannot import name 'disabled' from 'txl.app' (/home/asill/conda/envs/jpterm/lib/python3.12/site-packages/txl/app.py)

```

**Comment by davidbrochart** [comment]
Thanks for reporting the issue, #50 should fix it.
