### ISSUE TITLE
Unable to start jpterm due to ImportError from txl.app

### ISSUE THREAD

**Issue by jbdyn** [davidbrochart/jpterm#62]
Hi, nice project!

I wanted to try out `jpterm` and installed the package via pip

```shell
$ python -m venv env --upgrade-deps
$ source env/bin/activate
$ pip install jpterm
```

in a new `venv`, however when invoking

```shell
$ jpterm
```
I get the following ImportError:
```python
Traceback (most recent call last):
  File "/path/to/env/bin/jpterm", line 5, in <module>
    from jpterm.cli import main
  File "/path/to/env/lib/python3.11/site-packages/jpterm/cli.py", line 3, in <module>
    from txl.app import disabled
ImportError: cannot import name 'disabled' from 'txl.app' (/path/to/env/lib/python3.11/site-packages/txl/app.py)
```

I built the `txl` wheel seperately, as the source code in `txl/app.py` indeed has a `disabled` variable, but ran into dependency issues during installation:

```pip
$ pip install txl-0.1.22-py3-none-any.whl
...
ypywidgets-textual 0.2.1 requires textual>=0.41.0, but you have textual 0.40.0 which is incompatible.
Successfully installed textual-0.40.0 txl-0.1.22
```

Maybe you know a faster way than me to solve that?

Thank you for work (also pycrdt and all the other repos)!

**Comment by davidbrochart** [comment]
Thanks for the kind words! Could you post the output of `pip list`?

**Comment by jbdyn** [comment]
Sure! Starting with a completely new venv 
```
(env) $ pip install jpterm
```
<details>
<summary>
pip list (ImportError)
</summary>

```
Package              Version
-------------------- ----------
aiosqlite            0.19.0
anyio                3.7.1
asphalt              4.12.0
async-generator      1.10
async-timeout        4.0.3
asyncio-extras       1.3.2
certifi              2023.11.17
click                8.1.7
comm                 0.2.0
h11                  0.14.0
httpcore             0.17.3
httpx                0.25.1
httpx-ws             0.4.2
idna                 3.4
importlib-metadata   6.8.0
jpterm               0.1.22
jupyter-ydoc         1.1.1
linkify-it-py        2.0.2
markdown-it-py       3.0.0
mdit-py-plugins      0.4.0
mdurl                0.1.2
Pillow               10.1.0
pip                  23.3.1
plotext              5.2.8
pluggy               1.3.0
pycrdt               0.4.2
Pygments             2.17.1
pyte                 0.8.2
python-dateutil      2.8.2
pyzmq                25.1.1
reacttrs             0.1.4
rich                 13.7.0
rich-click           1.7.1
ruamel.yaml          0.18.5
ruamel.yaml.clib     0.2.8
setuptools           69.0.0
six                  1.16.0
sniffio              1.3.0
textual              0.41.0
textual-imageview    0.1.1
textual-plotext      0.2.1
traitlets            5.13.0
txl                  0.1.12
txl_cell             0.1.22
txl_console          0.1.22
txl_editors          0.1.22
txl_file_browser     0.1.22
txl_image_viewer     0.1.22
txl_jpterm           0.1.22
txl_kernel           0.1.22
txl_launcher         0.1.22
txl_local_contents   0.1.22
txl_local_kernels    0.1.22
txl_local_terminals  0.1.21
txl_markdown_viewer  0.1.22
txl_notebook_editor  0.1.22
txl_remote_contents  0.1.22
txl_remote_kernels   0.1.22
txl_remote_terminals 0.1.22
txl_terminal         0.1.22
txl_text_editor      0.1.22
txl_widgets          0.1.22
typing_extensions    4.8.0
uc-micro-py          1.0.2
wcwidth              0.2.10
wsproto              1.2.0
y-py                 0.6.2
ypy-websocket        0.12.4
ypywidgets           0.6.2
ypywidgets-textual   0.2.1
zipp                 3.17.0
```
</details>

and then calling

```
(env) $ pip install txl-0.1.22-py3-none-any.whl
```
<details>
<summary>
pip list (VersionConflict)
</summary>

```
Package               Version
--------------------- ----------
aiosqlite             0.19.0
anyio                 3.7.1
asphalt               4.12.0
async-generator       1.10
async-timeout         4.0.3
asyncio-extras        1.3.2
certifi               2023.11.17
click                 8.1.7
comm                  0.2.0
h11                   0.14.0
httpcore              0.17.3
httpx                 0.25.1
httpx-ws              0.4.2
idna                  3.4
importlib-metadata    6.8.0
jpterm                0.1.22
jupyter-ydoc          1.1.1
linkify-it-py         2.0.2
markdown-it-py        3.0.0
mdit-py-plugins       0.4.0
mdurl                 0.1.2
Pillow                10.1.0
pip                   23.3.1
plotext               5.2.8
pluggy                1.3.0
pycrdt                0.4.2
Pygments              2.17.1
pyte                  0.8.2
python-dateutil       2.8.2
pyzmq                 25.1.1
reacttrs              0.1.4
rich                  13.7.0
rich-click            1.7.1
ruamel.yaml           0.18.5
ruamel.yaml.clib      0.2.8
setuptools            69.0.0
six                   1.16.0
sniffio               1.3.0
textual               0.40.0
textual-imageview     0.1.1
textual-plotext       0.2.1
traitlets             5.13.0
tree-sitter           0.20.4
tree-sitter-languages 1.8.0
txl                   0.1.22
txl_cell              0.1.22
txl_console           0.1.22
txl_editors           0.1.22
txl_file_browser      0.1.22
txl_image_viewer      0.1.22
txl_jpterm            0.1.22
txl_kernel            0.1.22
txl_launcher          0.1.22
txl_local_contents    0.1.22
txl_local_kernels     0.1.22
txl_local_terminals   0.1.21
txl_markdown_viewer   0.1.22
txl_notebook_editor   0.1.22
txl_remote_contents   0.1.22
txl_remote_kernels    0.1.22
txl_remote_terminals  0.1.22
txl_terminal          0.1.22
txl_text_editor       0.1.22
txl_widgets           0.1.22
typing_extensions     4.8.0
uc-micro-py           1.0.2
wcwidth               0.2.10
wsproto               1.2.0
y-py                  0.6.2
ypy-websocket         0.12.4
ypywidgets            0.6.2
ypywidgets-textual    0.2.1
zipp                  3.17.0
```
</details>

with the VersionConflict being

```python
$ jpterm
...
pkg_resources.VersionConflict: (textual 0.40.0 (/path/to/env/lib/python3.11/site-packages), Requirement.parse('textual>=0.41.0'))
```

**Comment by davidbrochart** [comment]
You get the `ImportError` because you have `txl==0.1.12`, upgrading to `0.1.22` should fix it.
I need to find a better way for pinning all the dependencies, but basically `jpterm`, `txl` and all the `txl_*` plugins must have the same version.

**Comment by jbdyn** [comment]
Your comment made me curious, so I set up yet another fresh environment, but this time I installed `jpterm` with
```
$ pip install "jpterm>=0.1.22" "txl>=0.1.22"
```
and got a familiar JupyterLab TUI! 

So, the VersionConflict came just from me carelessly throwing a self-built package into an already populated environment.

I appreciate your immediate help and will have a look right away!
