### ISSUE TITLE
P3.8: cannot run: type object is not subscriptable

### ISSUE THREAD

**Issue by chris-aeviator** [davidbrochart/jpterm#82]
Steps:

1) activate a python 3.8 virtual env
2) pip install jpterm
3) run jpterm

```

❯ jpterm
Traceback (most recent call last):
  File "/home/my_user/micromamba/envs/my_env/bin/jpterm", line 5, in <module>
    from jpterm.cli import main
  File "/home/my_user/micromamba/envs/my_env/lib/python3.8/site-packages/jpterm/cli.py", line 3, in <module>
    from txl.cli import set_main, txl_main
  File "/home/my_user/micromamba/envs/my_env/lib/python3.8/site-packages/txl/cli.py", line 3, in <module>
    from .app import run
  File "/home/my_user/micromamba/envs/my_env/lib/python3.8/site-packages/txl/app.py", line 6, in <module>
    from txl import hooks
  File "/home/my_user/micromamba/envs/my_env/lib/python3.8/site-packages/txl/hooks.py", line 13, in <module>
    def component() -> Tuple[str, type[Component], Dict[str, Any]]:
TypeError: 'type' object is not subscriptable
```

**Comment by davidbrochart** [comment]
Jpterm [requires Python 3.10 at least](https://github.com/davidbrochart/jpterm/blob/ea3be08c887c50acf7568b17245d74846174fe45/pyproject.toml#L11).

**Comment by davidbrochart** [comment]
`pip` takes this information into account, and should install the right jpterm version depending on the Python version. The problem is with earlier jpterm versions. Since they were very early stage, I just deleted all versions<0.2.0.
